// --help
// Generated by W3D Shader Pre-processor, Kenny Mitchell - Westwood Studios, EA 2002

// NB: This is an intermediate build file, don't add to source control
DWORD --_elp_code[]={
0x00000000,	0x00000000
};
